### ISSUE TITLE
Bump guzzle version to 7

### ISSUE THREAD

**Issue by RatkoR** [crate/crate-pdo#108]
Hi all,

laravel 8 requires [guzzle 7](https://github.com/laravel/laravel/blob/master/composer.json#L14). Any chance you can bump the required guzzle to 7 as well?

**Comment by seut** [comment]
@RatkoR Thanks for reporting, we'll have a look. 
We also appreciate any contributions.

**Comment by seut** [comment]
We've bumped it and also released version `1.1.0` including this change.
