### ISSUE TITLE
Add compatibility with PHP 8.0

### ISSUE THREAD

**Issue by amotl** [crate/crate-pdo#115]
Hi there,

PHP 8.0.2 has been released and PHP 8.1.x is in the making. We might want to follow that. After adding this improvement here, we should follow up at https://github.com/crate/crate-dbal/issues/105.

At the same time, we might want to remove support for PHP 7.2, as it reached end of life (EOL) [1,2]. Because some signatures of the PDO interface have changed, this will probably make the support of PHP 7.3, PHP 7.4 and PHP 8.x easier.

With kind regards,
Andreas.

[1] https://www.php.net/supported-versions.php
[2] https://www.zend.com/blog/php-72-eol

**Comment by amotl** [comment]
#116 brings in PHP8 support. Due to the nature of the PDO compatibility layers, Coveralls reports
```
Coverage decreased (-12.4%) to 76.509% 
```

Apparently, Coveralls is not capable of merging coverage reports. We should consider migrating to Codecov, see also https://github.com/lemurheavy/coveralls-public/issues/613#issuecomment-244686345.

**Comment by amotl** [comment]
After integrating #116, we should issue a new release and then follow up at crate/crate-dbal#105.

**Comment by alexander-schranz** [comment]
Any update to this seems like #116 was merged but not released?

**Comment by amotl** [comment]
Thanks for the bump, Alexander. We will try to release a new version soon.

**Comment by amotl** [comment]
Dear Alexander,

CrateDB PDO Adapter 2.0.0 has been released and should be compatible with PHP8. Now, we will have to take care about the downstream repository, see https://github.com/crate/crate-dbal/issues/105.

With kind regards,
Andreas.
