### ISSUE TITLE
Interface "Crate\PDO\PDOInterface" not found

### ISSUE THREAD

**Issue by JulianMar** [crate/crate-pdo#127]
Hi I have an issue with crate-pdo. It seems like if you use `composer dump-autoload -a` the PDOInterface and the class alias in it can't be resolved.

For now we are switching to the `-o` optimization but it would be good to have a dedicated version for 8.x. As I don't see any other workaround after googling a bit.

**Comment by amotl** [comment]
Dear Julian,

thank you very much for reporting this. Do you have any specific suggestions how we can improve the situation? We will always be happy to accept corresponding patches.

With kind regards,
Andreas.

**Comment by JulianMar** [comment]
Hi Andreas,
thanks for your reply. I cooked up a solution to the problem in PR https://github.com/crate/crate-pdo/pull/128.
And would like some feedback. It'S a primitive solution but works till you can drop support for php 7.x in 2-3 Years

Thanks
Julian
