### ISSUE TITLE
Support for object fetch style

### ISSUE THREAD

**Issue by jeteon** [crate/crate-pdo#40]
The code currently does not support fetching results with style `PDO::FETCH_OBJ`. It would be really nice to have support for this added. I appreciate that it's not a major issue though.
##

**Comment by chaudum** [comment]
Hi @jeteon 
You're right, there is no support for `PDO::FETCH_OBJ` right now. We'll put it into our backlog, though. However I cannot give an estimation when this will be implemented then.

I think it would not be that difficult to implement, so we would be more than happy if you would like to contribute :)

**Comment by jeteon** [comment]
I understand. There's quite a lot of evolving surface area on Crate in addition to the core project and you may not have users of PHP on the team. 

I'd like to work on a PR but I didn't have time in the instant and wanted to at least put an issue down.

**Comment by tomsvogel** [comment]
PDO::FETCH_OBJ works now with 0.6.4
