### ISSUE TITLE
Remove dependency on guzzle 5.x.

### ISSUE THREAD

**Issue by roncemer** [crate/crate-pdo#44]
If you already have guzzle 6.x installed, and try to install crate-pdo, composer complains that it can't install guzzle-5.x because guzzle-6.x is already installed.

$ composer require crate/crate-pdo:~0.3.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for crate/crate-pdo ~0.3.1 -> satisfiable by crate/crate-pdo[0.3.1].
    - Conclusion: remove guzzlehttp/guzzle 6.2.0
    - Conclusion: don't install guzzlehttp/guzzle 6.2.0
    - crate/crate-pdo 0.3.1 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.2.0].
    - Installation request for guzzlehttp/guzzle == 6.2.0.0 -> satisfiable by guzzlehttp/guzzle[6.2.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by joemoe** [comment]
hi @roncemer, thanks for reporting this. we'll have a look at it and keep you postet. cheers, johannes

**Comment by bogensberger** [comment]
Hi @roncemer,

we updated the dependency to guzzle 6.x. https://github.com/crate/crate-pdo/commit/70ba64bfa4bec970542f9b9ace476c19c912375d and i release crate-pdo 0.5.0 just now.
