### ISSUE TITLE
Examples of INSERT/UPDATE object/array/geo_point

### ISSUE THREAD

**Issue by web64** [crate/crate-pdo#58]
It would be great to see some examples on how to use this library in PHP to INSERT/UPDATE non-standard fields like object, array, and geo_point . Thanks!

**Comment by chaudum** [comment]
hi @web64 
you're right, the documentation is not really covering CrateDB custom types. we'll update our documentation accordingly!
in the meantime you can take a look at https://github.com/crate/crate-pdo/blob/master/test/CrateIntegrationTest/PDO/PDOStatementTest.php#L284-L302 where  an `array` (works also for `geo_point`) and an `object` are inserted and selected.

**Comment by web64** [comment]
Thanks @chaudum those examples was exactly what I was looking for!

**Comment by christianbader** [comment]
@web64 the extended documentation will be available soon.
