### ISSUE TITLE
Error with: SELECT cast(id as string) AS id, * 

### ISSUE THREAD

**Issue by web64** [crate/crate-pdo#59]
Crate-PDO:  verison 0.6.1

Not an important issue as there is a quick workaround for it.

SELECT cast(id as string) AS id, * FROM mytable LIMIT 1
This query causes this error:
Message: array_combine(): Both parameters should have an equal number of elements
Filename: PDO/PDOStatement.php
Line Number: 399

Workaround is to use another name for the 'id' field : 
SELECT cast(id as string) AS id_str, * FROM mytable LIMIT 1

**Comment by chaudum** [comment]
hi @web64 
thanks for reporting the issue. we will have a look!

**Comment by bogensberger** [comment]
Hi @web64 
thanks for reporting this. There was an issue with fetching the same column twice. I fixed it and the issue should be solved with the next release, which will be done soon.

Here the commit with the fix if you are interested: https://github.com/crate/crate-pdo/pull/61/commits/1a828b3d04e404f5dcdf214bd45dbee9de09e4c6

**Comment by bogensberger** [comment]
Hi @web64 

i released crate-pdo 0.6.2 which contains the fix today.
