### ISSUE TITLE
Some INSERTs seem to fail randomly

### ISSUE THREAD

**Issue by christophpe** [crate/crate-pdo#68]
**CrateDB version:** 2.0.6

**JVM version:** OpenJDK 1.8.0_131

**OS version / environment description:** CentOS 7 (3.10.0-514.26.2.el7.x86_64)

**Problem description:**
Using PHP, some INSERT statements seem to fail randomly.

Relations are to be inserted, and it seems like about 50% of the queries pass, while the rest fails.

The error message is:
Crate Prepare Error: Code = 4000, Message = SQLActionException[SQLParseException: line 1:number: no viable alternative at input ',']

If you copy the queries without any change into the console in the AdminUI, every query succeeds.

The driver we use is the crate database driver (crate-pdo-0.6.3 (composer package)).

**Steps to reproduce:**
CREATE TABLE IF NOT EXISTS "company"."relation" (
"id_from" STRING,
"id_to" STRING,
PRIMARY KEY ("id_from", "id_to")
)
CLUSTERED BY ("id_from") INTO 8 SHARDS
WITH (
"blocks.metadata" = false,
"blocks.read" = false,
"blocks.read_only" = false,
"blocks.write" = false,
column_policy = 'strict',
number_of_replicas = '1',
"recovery.initial_shards" = 'quorum',
refresh_interval = 1000,
"routing.allocation.enable" = 'all',
"routing.allocation.total_shards_per_node" = -1,
"translog.durability" = 'REQUEST',
"translog.flush_threshold_size" = 536870912,
"translog.sync_interval" = 5000,
"unassigned.node_left.delayed_timeout" = 60000,
"warmer.enabled" = true,
"write.wait_for_active_shards" = 'all'
)

_INSERT that SUCCEEDS:_
INSERT INTO company.relation (id_from, id_to) VALUES ('413462662023162', '1691996757702397'), ('413462662023162', '359532474088827'), ('413462662023162', '1591614901072190');

_INSERT that FAILS:_
INSERT INTO company.relation (id_from, id_to) VALUES ('413462662023162', '1691996757702397'), ('413462662023162', '359532474088827'), ('413462662023162', '1591614901072190'), ('413462662023162', '42199325465'), ('413462662023162', '440195839442412'), ('413462662023162', '106197822745388');

**Comment by dornbirndevelops** [comment]
@christophpe 

I've tested your configuration and it worked fine for me. I couldn't reproduce the given example. Although when altering the failing query in a way that the 2nd or following record has an empty first column, Crate will complain about a record with a partial empty primary key and will therefore not insert it.

The query I used to get the error was (notice that the first column of record 3 is empty):
`INSERT INTO company.relation (id_from, id_to) VALUES ('1', '1'), ('2', '2'), (, '3'), ('4', '4'), ('5', '5'), ('6', '6');`

To make sure the query will be correct, it is recommended to make use of [prepared statements](http://php.net/manual/en/pdostatement.bindparam.php).

Hope this helps

**Comment by christophpe** [comment]
Can you test it by trying to use around 100 such insert statements and see if any of them fail?

None of the values are empty - I have checked that already.

Thank you a lot for trying so far!

**Comment by dornbirndevelops** [comment]
@christophpe 
Thank you for the fast reply! I will try tomorrow!

Just to get this right: the insert statement itself can remain about the same length of 6 records. I should just try to invoke it more often rapidly.

Dare i ask how these values are generated? And are these Insert-Statements done asynchronously?

**Comment by christophpe** [comment]
@dornbirndevelops 

Exactly.
In my experience, the amount of records to be inserted in the value-clause do not affect the result.
This is just about increasing the chance of some queries to fail (by adding more of them).

The relation table connects entities hat are collected with a data crawler. An INSERT means that a crawler has found a new relation between two of these entities. I hope that makes it somewhat clear.

No, they aren't async.

**Comment by dornbirndevelops** [comment]
@christophpe 

I've made a stress test of the described scenario. I've ran it several times, but I wasn't able to get an error unfortunately.
Please be certain that the values used at the time of insert are not empty!
Not sure if it helps, but here's the code I used (forgive me for being new to PHP):
`<?php
require 'vendor/autoload.php';
use Crate\PDO\PDO as PDO;
$dsn = 'crate:localhost:4200';
$connection = new PDO($dsn, null, null, null);

$qry = $connection->prepare("DELETE FROM company.relation");
$qry->execute();

sleep(3);

$qry = $connection->prepare("SELECT COUNT(*) FROM company.relation");
$qry->execute();
$old_count = $qry->fetchAll();

sleep(3);

for($x = 0; $x < 6*10000; $x++) {  
    $qry = $connection->prepare(
        "INSERT INTO company.relation (id_from, id_to) 
        VALUES
        (?, ?),
        (?, ?),
        (?, ?),
        (?, ?),
        (?, ?),
        (?, ?)"
        );

    $qry->bindParam(1, $x, PDO::PARAM_INT);
    $qry->bindParam(2, $x, PDO::PARAM_INT);
    $x++;
    $qry->bindParam(3, $x, PDO::PARAM_INT);
    $qry->bindParam(4, $x, PDO::PARAM_INT);
    $x++;
    $qry->bindParam(5, $x, PDO::PARAM_INT);
    $qry->bindParam(6, $x, PDO::PARAM_INT);
    $x++;
    $qry->bindParam(7, $x, PDO::PARAM_INT);
    $qry->bindParam(8, $x, PDO::PARAM_INT);
    $x++;
    $qry->bindParam(9, $x, PDO::PARAM_INT);
    $qry->bindParam(10, $x, PDO::PARAM_INT);
    $x++;
    $qry->bindParam(11, $x, PDO::PARAM_INT);
    $qry->bindParam(12, $x, PDO::PARAM_INT);

    $qry->execute();
}

sleep(3);

$qry = $connection->prepare("SELECT COUNT(*) FROM company.relation");
$qry->execute();
$new_count = $qry->fetchAll();

print_r($old_count);
print_r($new_count);
?>`

**Comment by dornbirndevelops** [comment]
@christophpe 

What's the size of the cluster? Where is it hosted? Is there something in the logs? Is the cluster busy (highload, lot of memory consumption)? How many inserts do you do per seconds? Are there any parallel reads?

**Comment by christophpe** [comment]
@dornbirndevelops

I have now changed to using prepared statements similar to your code example - thanks for that by the way.

That has done the trick, the errors are gone.

That still does not explain to me why the error occured, since I am still pretty sure there were no empty columns actually.

Nonetheless, my issue is fixed for now.

Thanks a lot for your help!

About the info you requested (maybe it helps if you do find some kind of error):
The cluster has 8 nodes. The load / memory consumption should not be too high, it is just a dev-cluster, not too much going on right now.
I probably did around 1-100 inserts per second (it varies a lot unfortunately). 
There are no parallel operations
